modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/infernalexp/Second-Chance-Forge/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="secondchanceforge" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

 # A display name for the mod
displayName="Second Chance Forge" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="Second_Chance_Logo.png" #optional

# A text field displayed in the mod UI
credits="See the description!" #optional

# A text field displayed in the mod UI
authors="HellionGames" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod designed for better accessibility, while still managing to stay within the frame of Vanilla.
This mod adds a feature that allows you to stay at half a heart when you would've been one shot, and a feature to allow you to jump for a few seconds after falling off a block!
Both features are toggleable through the config.

This is a Forge port of the original Fabric mod by Zoeytheegoist.

Coder:
- HellionGames

Original:
- Zoeytheegoist

Special Thanks:
-Nekomaster1000 for the Logo Render
'''

[[dependencies.secondchanceforge]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.secondchanceforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
