name: Publish

on:
  push:
    tags:
      - '1.16.5/*'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/

      - name: Publish to Modrinth
        run: ./gradlew publishModrinth
        env:
          MODRINTH: ${{ secrets.MODRINTH_TOKEN }}

      - name: Publish to Curseforge
        run: ./gradlew curseforge
        env:
          CURSEFORGE: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/libs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }} for Minecraft 1.16.5

      - name: Publish to Infernal Studios Maven
        run: ./gradlew publish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}